language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

# command to install dependencies
install:
    - pip install -r test${TRAVIS_PYTHON_VERSION:0:1}_requirements.txt
    - pip install coveralls

# command to run tests
script:
    - py.test --cov=restless

# command to notify coveralls
after_success:
    - coveralls
