language: python

python:
  - "3.3"
  - "2.7"

# command to install dependencies
install:
    - pip install -r test${TRAVIS_PYTHON_VERSION:0:1}_requirements.txt

# command to run tests
script:
    - nosetests
